[build]
  command = "npm install --legacy-peer-deps tailwindcss postcss autoprefixer @babel/plugin-transform-react-jsx && NODE_OPTIONS='--require=./vite-cjs-fix.js' node netlify-build.js"
  publish = "dist"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  SKIP_PREFLIGHT_CHECK = "true"
  DISABLE_ESLINT_PLUGIN = "false"
  CI = "false"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NODE_VERSION = "18.18.0"
