export { HeroSection } from './HeroSection'
export { SocialProofBar } from './SocialProofBar'
export { HowItWorks } from './HowItWorks'
export { StatsSection } from './StatsSection'
export { FeaturesSection } from './FeaturesSection'
export { TestimonialsSection } from './TestimonialsSection'
export { CTASection } from './CTASection'
export { LandingPageClient } from './LandingPageClient'
export { default as DrSimeonShowcase } from './DrSimeonShowcase'
