/*
  # Doctor.mx Connect Program Schema

  1. New Tables
    - `referral_links` - Stores referral links generated by doctors
    - Add fields to doctors table for referral program

  2. Security
    - Enable RLS on new tables
    - Add policies for authenticated users

  3. Changes
    - Add necessary indexes for performance
    - Add foreign key relationships
*/

-- Add new fields to doctors table
ALTER TABLE doctors 
ADD COLUMN IF NOT EXISTS joined_via_referral boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS referral_id uuid,
ADD COLUMN IF NOT EXISTS is_premium boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS premium_until timestamptz;

-- Create referral links table
DO $$ BEGIN
  CREATE TABLE IF NOT EXISTS referral_links (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id uuid REFERENCES doctors(id) ON DELETE CASCADE,
    name text,
    code text UNIQUE NOT NULL,
    usage_count integer DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    last_used_at timestamptz,
    expires_at timestamptz,
    max_uses integer DEFAULT NULL,
    is_active boolean DEFAULT true
  );
EXCEPTION
  WHEN duplicate_table THEN NULL;
END $$;

-- Create referral tracking table
DO $$ BEGIN
  CREATE TABLE IF NOT EXISTS referral_conversions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    referrer_id uuid REFERENCES doctors(id) ON DELETE SET NULL,
    referred_id uuid REFERENCES doctors(id) ON DELETE SET NULL,
    referral_link_id uuid REFERENCES referral_links(id) ON DELETE SET NULL,
    conversion_date timestamptz DEFAULT now(),
    premium_status boolean DEFAULT true,
    premium_expiry timestamptz,
    notes text
  );
EXCEPTION
  WHEN duplicate_table THEN NULL;
END $$;

-- Create a function to handle premium status expiration
CREATE OR REPLACE FUNCTION check_premium_expiration()
RETURNS TRIGGER AS $$
BEGIN
  -- If premium_until date has passed, set is_premium to false
  IF NEW.premium_until IS NOT NULL AND NEW.premium_until < NOW() THEN
    NEW.is_premium := false;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to check premium expiration on update
DO $$ BEGIN
  CREATE TRIGGER check_doctor_premium_expiration
  BEFORE UPDATE ON doctors
  FOR EACH ROW
  EXECUTE FUNCTION check_premium_expiration();
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Create function to increment usage count
CREATE OR REPLACE FUNCTION increment(row_id uuid, increment_amount integer)
RETURNS integer AS $$
DECLARE
  new_count integer;
BEGIN
  UPDATE referral_links
  SET usage_count = usage_count + increment_amount
  WHERE id = row_id
  RETURNING usage_count INTO new_count;
  
  RETURN new_count;
END;
$$ LANGUAGE plpgsql;

-- Enable Row Level Security
ALTER TABLE referral_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_conversions ENABLE ROW LEVEL SECURITY;

-- Policy for referral_links
CREATE POLICY "Doctors can view their own referral links"
  ON referral_links
  FOR SELECT
  USING (doctor_id = auth.uid() OR 
         doctor_id IN (SELECT id FROM doctors WHERE user_id = auth.uid()));

CREATE POLICY "Doctors can create their own referral links"
  ON referral_links
  FOR INSERT
  WITH CHECK (doctor_id IN (SELECT id FROM doctors WHERE user_id = auth.uid()));

CREATE POLICY "Doctors can update their own referral links"
  ON referral_links
  FOR UPDATE
  USING (doctor_id = auth.uid() OR 
         doctor_id IN (SELECT id FROM doctors WHERE user_id = auth.uid()));

-- Create indexes
CREATE INDEX IF NOT EXISTS referral_links_doctor_id_idx ON referral_links(doctor_id);
CREATE INDEX IF NOT EXISTS referral_links_code_idx ON referral_links(code);
CREATE INDEX IF NOT EXISTS doctors_referral_id_idx ON doctors(referral_id);
CREATE INDEX IF NOT EXISTS doctors_premium_until_idx ON doctors(premium_until);
CREATE INDEX IF NOT EXISTS referral_conversions_referrer_id_idx ON referral_conversions(referrer_id);
CREATE INDEX IF NOT EXISTS referral_conversions_referred_id_idx ON referral_conversions(referred_id);